# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73215467097e5401ff22c5de8d767fb68b2ccbafd10abf01bf75711d4bb83dce8abf987cd7f4a22efcbd3cf4a53a0985b2c9394588994541189bf2b48adba729

test:
  secret_key_base: e44e1818a4ee8f59e6e01cd952077d51089d495f067fc51f2c0eff6545a162b94973fe22d9f51c3296e1ce3957221367d8db374e577ae5c96898ae02cd475874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
